// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLtuOiSkGhSfqcp6twhPDxdzZo_OSe97U',
    appId: '1:856863072894:web:bf9f6c7ffc8fb5002f6e2f',
    messagingSenderId: '856863072894',
    projectId: 'carecall-assist',
    authDomain: 'carecall-assist.firebaseapp.com',
    storageBucket: 'carecall-assist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbwoRTvXKQCFK0Ecx7qrA8vkwm7UM9kBo',
    appId: '1:856863072894:android:0599813b42e689512f6e2f',
    messagingSenderId: '856863072894',
    projectId: 'carecall-assist',
    storageBucket: 'carecall-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDyW8QQA4Im4ER_U0SFMYXs0Q5F3vDGU',
    appId: '1:856863072894:ios:6383ec68519925b62f6e2f',
    messagingSenderId: '856863072894',
    projectId: 'carecall-assist',
    storageBucket: 'carecall-assist.firebasestorage.app',
    iosBundleId: 'com.example.carecallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWDyW8QQA4Im4ER_U0SFMYXs0Q5F3vDGU',
    appId: '1:856863072894:ios:6383ec68519925b62f6e2f',
    messagingSenderId: '856863072894',
    projectId: 'carecall-assist',
    storageBucket: 'carecall-assist.firebasestorage.app',
    iosBundleId: 'com.example.carecallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLtuOiSkGhSfqcp6twhPDxdzZo_OSe97U',
    appId: '1:856863072894:web:c86e120e5c1e1e4c2f6e2f',
    messagingSenderId: '856863072894',
    projectId: 'carecall-assist',
    authDomain: 'carecall-assist.firebaseapp.com',
    storageBucket: 'carecall-assist.firebasestorage.app',
  );
}
